package co.dhan.dto;

import co.dhan.constant.*;
import lombok.Data;

import java.math.BigDecimal;

@Data
public class Order {
    /**
     * User specific identification generated by Dhan
     */
    private String orderId;
    /**
     * The user/partner generated id for tracking back.
     * Its length >=0 and <=25 characters.
     */
    private String correlationId;
    private TransactionType transactionType;
    private OrderStatus orderStatus;

    /**
     * Exchange standard identification for each scrip
     */
    private String securityId;
    private String tradingSymbol;
    //    private String exchangeOrderId;
    private ExchangeSegment exchangeSegment;
    private ProductType productType;
    private OrderType orderType;
    private Validity validity;

    private int quantity;
    /**
     * Number shares visible in the market depth
     */
    private int disclosedQuantity;
    private BigDecimal price;
    private BigDecimal triggerPrice;

    private boolean afterMarketOrder;
    private LegName legName;
    private BigDecimal boProfitValue;
    private BigDecimal boStopLossValue;

    private String createTime;
    private String updateTime;
    private String exchangeTime;

    private String drvExpiryDate;
    private OptionType drvOptionType;
    private BigDecimal drvStrikePrice;

    private String omsErrorCode;
    private String omsErrorDescription;

    private String algoId;

    private int filledQty;
    private int remainingQuantity;
    private BigDecimal averageTradedPrice;

    //    private OrderFlag orderFlag;
    //    private AMOTime amoTime;
    //    private int quantity1;
    //    private BigDecimal price1;
    //    private BigDecimal triggerPrice1;

}
